language: node_js
node_js:
  - "8"
install:
  - npm install
  - npm install -g codecov
script:
  - npm run pretest
  - npm run assets
  - npm run test:silent && codecov

cache:
  bundler: true
  directories:
  - node_modules

# ignore:
#   - *.md