environment:
  nodejs_version: "8"

# Install scripts. (runs after repo cloning)
install:
  - echo {"app":{"js":"/assets/app.ca83982d2615c67aa736.js"},"vendor":{"js":"/assets/vendor.ca83982d2615c67aa736.js"}} > assets.json
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install sharp
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off

cache:
  - node_modules                        # local npm modules


skip_commits:
  files:
    - '*.md'
    - '**/*.md'
    - '.vscode/'