version: 1.0.{build}
max_jobs: 4
environment:
  nodejs_version: "8"
platform: x64

# Install scripts. (runs after repo cloning)
install:
  - echo {"app":{"js":"/assets/app.js"},"vendor":{"js":"/assets/vendor.js"}} > assets.json
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version x64
  # install modules
  # - rd -r node_modules
  - npm install
  - npm rebuild

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - npm run pretest
  # run tests
  - npm run test:silent

# Don't actually build.
build:
  verbosity: minimal

cache:
  #- node_modules


skip_commits:
  files:
    - '*.md'
    - '**/*.md'
    - '.vscode/'